membersrvc:
  container_name: member
  image: hyperledger/fabric-membersrvc:latest
  ports:
    - "7054:7054"
  command: membersrvc
vp0:
  container_name: vp0
  image: hyperledger/fabric-peer:latest
  ports:
    - "7050:7050"
    - "7051:7051"
    - "7052:7052"
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
  environment:
    CORE_PEER_ADDRESSAUTODETECT: 'true'
#    CORE_VM_ENDPOINT: http://172.17.0.1:2376
#    CORE_VM_ENDPOINT: http://10.142.76.103:2376
#    CORE_VM_ENDPOINT: unix:///var/run/docker.sock
#    CORE_VM_ENDPOINT: http://127.0.0.1:2375
    CORE_LOGGING_LEVEL: DEBUG
    CORE_PEER_ID: vp0
    CORE_PEER_PKI_ECA_PADDR: membersrvc:7054
    CORE_PEER_PKI_TCA_PADDR: membersrvc:7054
    CORE_PEER_PKI_TLSCA_PADDR: membersrvc:7054
    CORE_PEER_VALIDATOR_CONSENSUS_PLUGIN: pbft
    CORE_PBFT_GENERAL_MODE: batch
    CORE_SECURITY_ENABLED: 'true'
    CORE_SECURITY_ENROLLID: test_vp0
    CORE_SECURITY_ENROLLSECRET: MwYpmSRjupbT
    CORE_CHAINCODE_GOLANG_DOCKERFILE: |
        FROM hyperledger/fabric-baseimage:latest
        ENV GOPATH=/opt/gopath
        ENV GOROOT=/opt/go
        ENV PATH=$$PATH:$$GOROOT/bin:$$GOPATH/bin
        COPY src $$GOPATH/src
        WORKDIR $$GOPATH
  links:
    - membersrvc
  command: sh -c "sleep 5; peer node start"
vp1:
  container_name: vp1
  image: hyperledger/fabric-peer:latest
  ports:
    - "7150:7050"
    - "7151:7051"
    - "7152:7052"
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
  environment:
    CORE_PEER_ADDRESSAUTODETECT: 'true'
    CORE_PEER_DISCOVERY_ROOTNODE: vp0:7051
#    CORE_VM_ENDPOINT: http://172.17.0.1:2376
#    CORE_VM_ENDPOINT: http://10.142.76.103:2376
#    CORE_VM_ENDPOINT: unix:///var/run/docker.sock
#    CORE_VM_ENDPOINT: http://127.0.0.1:2375
    CORE_LOGGING_LEVEL: DEBUG
    CORE_PEER_ID: vp1
    CORE_PEER_PKI_ECA_PADDR: membersrvc:7054
    CORE_PEER_PKI_TCA_PADDR: membersrvc:7054
    CORE_PEER_PKI_TLSCA_PADDR: membersrvc:7054
    CORE_PEER_VALIDATOR_CONSENSUS_PLUGIN: pbft
    CORE_PBFT_GENERAL_MODE: batch
    CORE_SECURITY_ENABLED: 'true'
    CORE_SECURITY_ENROLLID: test_vp1
    CORE_SECURITY_ENROLLSECRET: 5wgHK9qqYaPy
    CORE_CHAINCODE_GOLANG_DOCKERFILE: |
        FROM hyperledger/fabric-baseimage:latest
        ENV GOPATH=/opt/gopath
        ENV GOROOT=/opt/go
        ENV PATH=$$PATH:$$GOROOT/bin:$$GOPATH/bin
        COPY src $$GOPATH/src
        WORKDIR $$GOPATH
  links:
    - membersrvc
    - vp0
  command: sh -c "sleep 10; peer node start"
vp2:
  container_name: vp2
  image: hyperledger/fabric-peer:latest
  ports:
    - "7250:7050"
    - "7251:7051"
    - "7252:7052" 
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
  environment:
    CORE_PEER_ADDRESSAUTODETECT: 'true'
    CORE_PEER_DISCOVERY_ROOTNODE: vp0:7051
#    CORE_VM_ENDPOINT: http://172.17.0.1:2376
#    CORE_VM_ENDPOINT: http://10.142.76.103:2376
#    CORE_VM_ENDPOINT: unix:///var/run/docker.sock
#    CORE_VM_ENDPOINT: http://127.0.0.1:2375
    CORE_LOGGING_LEVEL: DEBUG
    CORE_PEER_ID: vp2
    CORE_PEER_PKI_ECA_PADDR: membersrvc:7054
    CORE_PEER_PKI_TCA_PADDR: membersrvc:7054
    CORE_PEER_PKI_TLSCA_PADDR: membersrvc:7054
    CORE_PEER_VALIDATOR_CONSENSUS_PLUGIN: pbft
    CORE_PBFT_GENERAL_MODE: batch
    CORE_SECURITY_ENABLED: 'true'
    CORE_SECURITY_ENROLLID: test_vp2
    CORE_SECURITY_ENROLLSECRET: vQelbRvja7cJ
    CORE_CHAINCODE_GOLANG_DOCKERFILE: |
        FROM hyperledger/fabric-baseimage:latest
        ENV GOPATH=/opt/gopath
        ENV GOROOT=/opt/go
        ENV PATH=$$PATH:$$GOROOT/bin:$$GOPATH/bin
        COPY src $$GOPATH/src
        WORKDIR $$GOPATH
  links:
    - membersrvc
    - vp0
    - vp1
  command: sh -c "sleep 15; peer node start"
vp3:
  container_name: vp3
  image: hyperledger/fabric-peer:latest
  ports:
    - "7350:7050"
    - "7351:7051"
    - "7352:7052"
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
  environment:
    CORE_PEER_ADDRESSAUTODETECT: 'true'
    CORE_PEER_DISCOVERY_ROOTNODE: vp0:7051
#    CORE_VM_ENDPOINT: http://172.17.0.1:2376
#    CORE_VM_ENDPOINT: http://10.142.76.103:2376
#    CORE_VM_ENDPOINT: unix:///var/run/docker.sock
#    CORE_VM_ENDPOINT: http://127.0.0.1:2375
    CORE_LOGGING_LEVEL: DEBUG
    CORE_PEER_ID: vp3
    CORE_PEER_PKI_ECA_PADDR: membersrvc:7054
    CORE_PEER_PKI_TCA_PADDR: membersrvc:7054
    CORE_PEER_PKI_TLSCA_PADDR: membersrvc:7054
    CORE_PEER_VALIDATOR_CONSENSUS_PLUGIN: pbft
    CORE_PBFT_GENERAL_MODE: batch
    CORE_SECURITY_ENABLED: 'true'
    CORE_SECURITY_ENROLLID: test_vp3
    CORE_SECURITY_ENROLLSECRET: 9LKqKH5peurL
    CORE_CHAINCODE_GOLANG_DOCKERFILE: |
        FROM hyperledger/fabric-baseimage:latest
        ENV GOPATH=/opt/gopath
        ENV GOROOT=/opt/go
        ENV PATH=$$PATH:$$GOROOT/bin:$$GOPATH/bin
        COPY src $$GOPATH/src
        WORKDIR $$GOPATH
  links:
    - membersrvc
    - vp0
    - vp1
    - vp2
  command: sh -c "sleep 20; peer node start"

